# Generated by Django 5.2.7 on 2025-10-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_guild_alter_player_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skills',
        ),
    ]
